name: CI with SonarQube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=secure-devops-app
          -Dsonar.organization=your-org
          -Dsonar.sources=./backend
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
